worker_processes auto;

error_log /dev/stderr notice;
pid       /tmp/nginx.pid;

events {
    worker_connections 1024;
}

http {
    proxy_temp_path       /tmp/proxy_temp;
    client_body_temp_path /tmp/client_temp;
    fastcgi_temp_path     /tmp/fastcgi_temp;
    uwsgi_temp_path       /tmp/uwsgi_temp;
    scgi_temp_path        /tmp/scgi_temp;

    include      /etc/nginx/mime.types;
    default_type application/octet-stream;

    access_log /dev/stdout;

    sendfile on;

    keepalive_timeout 65;

    server {
        listen 8080;
        server_tokens off;
        absolute_redirect off;

        root /app;
        index index.html;

        gzip on;
        gzip_vary on;
        gzip_types text/plain text/css application/json application/javascript text/xml application/xml text/javascript image/svg+xml;

        location / {
            try_files $uri $uri/ /index.html;
        }
    }
}
