name: Publish beta
on:
  push:
    branches:
      - main

jobs:
  publish:
    name: Publish to package registry
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.15.0'
          registry-url: 'https://npm.pkg.github.com'
      - name: Bump version
        run: |
          git config --global user.name '${{ github.actor }}'
          git config --global user.email '${{ github.actor }}@users.noreply.github.com'
          npm version prerelease --preid beta
      - name: Publish package
        id: publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
