name: Publish package
on:
  push:
    branches:
      - main
jobs:
  deploy-docker-image:
    if: "contains(github.event.head_commit.message, 'release:publish')"
    name: Publish package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 16.x
          registry-url: https://npm.pkg.github.com/
          scope: "@navikt"
      - name: Publish package
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
