name: Publish REACT package to GPR
on:
  workflow_dispatch:

jobs:
  deploy-docker-image:
    name: Publish package
    runs-on: ubuntu-latest
    env:
      NODE_ENV: development
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
      - name: Npm install
        run: npm --workspace=src/packages/arbeidsplassen-react install
      - name: Build package
        run: npm --workspace=src/packages/arbeidsplassen-react run build
      - name: Publish package
        run: npm --workspace=src/packages/arbeidsplassen-react publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
