name: Publish CSS package
on:
  workflow_dispatch:
  
jobs:
  deploy-docker-image:
    name: Publish package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 16.x
          registry-url: https://npm.pkg.github.com/
          scope: "@navikt"
      - name: Install
        run: npm install
      - name: Update version
        run: npm --workspace=css version patch
      - name: Build
        run: npm run build
      - name: Publish package
        run: npm --workspace=css publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
