name: UI Tests

on:
  push:
    branches: ['**']
  pull_request:

jobs:
  test:
    name: Run Storybook tests
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: false

      - uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"

      - name: Install dependencies
        run: |
          pnpm config set @navikt:registry https://npm.pkg.github.com
          pnpm config set //npm.pkg.github.com/:_authToken $NODE_AUTH_TOKEN
          pnpm install --frozen-lockfile
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Playwright browsers
        run: pnpm exec playwright install chromium --with-deps

      - name: Run Storybook tests
        run: pnpm test-storybook
